<?php
/**
 * Creates (or reuses) a WooCommerce REST API key for local Andiko dev.
 * Run via: wp eval-file create-api-key.php
 */

$output = getenv('WOO_CREDENTIALS_FILE') ?: '/output/credentials.env';
$description = 'Andiko ERP Dev';

if (! function_exists('wc')) {
    fwrite(STDERR, "WooCommerce is not loaded.\n");
    exit(1);
}

global $wpdb;
$table = $wpdb->prefix . 'woocommerce_api_keys';

$existing_id = $wpdb->get_var(
    $wpdb->prepare("SELECT key_id FROM {$table} WHERE description = %s LIMIT 1", $description)
);

$store_url = getenv('WOO_STORE_URL') ?: 'http://localhost:8080';
$admin_user = getenv('WOO_ADMIN_USER') ?: 'admin';
$admin_pass = getenv('WOO_ADMIN_PASSWORD') ?: 'admin';

if ($existing_id && file_exists($output)) {
    echo "API key already exists (key_id={$existing_id}). Reusing {$output}\n";
    exit(0);
}

$user_id = (int) $wpdb->get_var(
    $wpdb->prepare("SELECT ID FROM {$wpdb->users} WHERE user_login = %s LIMIT 1", $admin_user)
);
if ($user_id <= 0) {
    fwrite(STDERR, "Admin user not found: {$admin_user}\n");
    exit(1);
}

$consumer_key    = 'ck_' . bin2hex(random_bytes(16));
$consumer_secret = 'cs_' . bin2hex(random_bytes(16));

$wpdb->insert(
    $table,
    [
        'user_id'         => $user_id,
        'description'     => $description,
        'permissions'     => 'read_write',
        'consumer_key'    => wc_api_hash($consumer_key),
        'consumer_secret' => $consumer_secret,
        'truncated_key'   => substr($consumer_key, -7),
    ],
    ['%d', '%s', '%s', '%s', '%s', '%s']
);

if (! $wpdb->insert_id) {
    fwrite(STDERR, "Failed to insert API key.\n");
    exit(1);
}

$lines = [
    '# Generated by infra/docker/woocommerce/bootstrap.sh — safe to regenerate with: docker compose run --rm woo-init',
    'WOO_STORE_URL=' . $store_url,
    'WOO_CONSUMER_KEY=' . $consumer_key,
    'WOO_CONSUMER_SECRET=' . $consumer_secret,
    'WOO_ADMIN_USER=' . $admin_user,
    'WOO_ADMIN_PASSWORD=' . $admin_pass,
    '',
    '# Andiko site modal → Conexión:',
    '#   URL de la tienda: ' . $store_url,
    '#   Consumer Key / Secret: values above',
    '#',
    '# Webhooks (WordPress in Docker → Andiko on host): set in .env.local',
    '#   AUTH_URL=http://host.docker.internal:3000',
    '#',
    '# Poll orders/stock manually (dev, no CRON_SECRET):',
    '#   curl -X POST http://localhost:3000/api/v1/integrations/woocommerce/sync',
];

file_put_contents($output, implode("\n", $lines) . "\n");
chmod($output, 0600);

echo "Wrote {$output}\n";
